"""
templates.py — Built-in task templates for Pantheon COO OS.
Includes PantheonMed (medical) vertical templates.
"""
from __future__ import annotations

import re
from typing import Any, Optional

# Valid industries for registration (stored on users.industry)
INDUSTRIES = frozenset({"medical", "retail", "agency", "tech", "other"})

TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "daily_report",
        "category": "reporting",
        "title": "Daily Performance Report",
        "description": "Generate a daily summary report and save to workspace",
        "command": "Generate a daily performance report with date, key metrics summary, and save it as /tmp/pantheon_v2/reports/daily_{date}.md",
        "tags": ["report", "daily", "automatic"],
        "estimated_minutes": 2,
        "variables": ["date"],
    },
    {
        "id": "website_scrape",
        "category": "research",
        "title": "Website Content Scraper",
        "description": "Scrape and save content from any website",
        "command": "Navigate to {url}, extract all main content text, and save to /tmp/pantheon_v2/scraped_{domain}.txt",
        "variables": ["url", "domain"],
        "tags": ["scrape", "research", "web"],
        "estimated_minutes": 3,
    },
    {
        "id": "competitor_pricing",
        "category": "research",
        "title": "Competitor Price Check",
        "description": "Check pricing from multiple competitor websites",
        "command": "Visit these websites: {urls}, find their pricing pages, extract all pricing tiers and amounts, create a comparison table and save as /tmp/pantheon_v2/competitor_pricing.md",
        "variables": ["urls"],
        "tags": ["pricing", "competitor", "research"],
        "estimated_minutes": 8,
    },
    {
        "id": "server_health",
        "category": "devops",
        "title": "Server Health Check",
        "description": "Check disk, memory, CPU and running processes",
        "command": "Check system health: disk usage, memory usage, CPU load, list top processes by memory, and save a health report to /tmp/pantheon_v2/health_{timestamp}.txt",
        "tags": ["server", "health", "monitoring"],
        "estimated_minutes": 1,
        "variables": ["timestamp"],
    },
    {
        "id": "code_generator",
        "category": "build",
        "title": "Python Script Generator",
        "description": "Generate and save a Python script for any task",
        "command": "Write a Python script that {description}, save it as /tmp/pantheon_v2/scripts/{filename}.py, then run it and show the output",
        "variables": ["description", "filename"],
        "tags": ["python", "code", "build"],
        "estimated_minutes": 4,
    },
    {
        "id": "build_and_run",
        "category": "build",
        "title": "Build, Fix & Run Code",
        "description": "Generate code, run automatically, fix errors, and show working output",
        "command": "Write a {language} script that {task}. Run it automatically, fix any errors, show me the working output.",
        "variables": ["language", "task"],
        "tags": ["code", "auto-fix", "run"],
        "estimated_minutes": 6,
    },
    {
        "id": "fix_github_issue",
        "category": "build",
        "title": "Fix GitHub Issue",
        "description": "Pull repo, locate bug, fix, test, and push back",
        "command": "Go to my GitHub repo {repo_url}, find the bug causing {issue}, fix it, test the fix, push the solution.",
        "variables": ["repo_url", "issue"],
        "tags": ["github", "fix", "autonomous"],
        "estimated_minutes": 15,
    },
    {
        "id": "full_stack_deploy",
        "category": "build",
        "title": "Build Full Stack App",
        "description": "Build full app (frontend+backend+db), auto-fix errors, deploy to Railway",
        "command": "Build a complete {app_type} application for {purpose}. Include frontend, backend, database. Fix all errors automatically. Deploy to Railway. Return live URL.",
        "variables": ["app_type", "purpose"],
        "tags": ["fullstack", "deploy", "autonomous"],
        "estimated_minutes": 35,
    },
    {
        "id": "email_report",
        "category": "communicate",
        "title": "Email a Report",
        "description": "Generate a report and email it",
        "command": "Create a detailed report about {topic}, format it as HTML, and send it to {email}",
        "variables": ["topic", "email"],
        "tags": ["email", "report", "communicate"],
        "estimated_minutes": 3,
    },
    {
        "id": "weekly_summary",
        "category": "reporting",
        "title": "Weekly Summary",
        "description": "Generate weekly task summary from COO history",
        "command": "Analyze the last 7 days of work from task history, identify patterns, summarize what was accomplished, what failed, and what should be prioritized next week. Save as /tmp/pantheon_v2/weekly_summary.md",
        "tags": ["weekly", "summary", "review"],
        "estimated_minutes": 3,
    },
    {
        "id": "file_organizer",
        "category": "build",
        "title": "Workspace File Organizer",
        "description": "List and organize files in workspace",
        "command": "List all files in /tmp/pantheon_v2/, group them by type and date, identify files older than 7 days, create an index file at /tmp/pantheon_v2/INDEX.md",
        "tags": ["files", "organize", "workspace"],
        "estimated_minutes": 2,
    },
    {
        "id": "sheets_export",
        "category": "reporting",
        "title": "Export Data to Google Sheets",
        "description": "Write report data to a Google Sheet",
        "command": "Read the file at {file_path}, parse the data rows, and write them to Google Sheets spreadsheet {spreadsheet_id} starting at range Sheet1!A1",
        "variables": ["file_path", "spreadsheet_id"],
        "tags": ["sheets", "export", "google"],
        "estimated_minutes": 3,
    },
    {
        "id": "sheets_read_report",
        "category": "analyze",
        "title": "Analyze Google Sheet Data",
        "description": "Read a Google Sheet and generate analysis report",
        "command": "Read data from Google Sheets spreadsheet {spreadsheet_id} range {range}, analyze the data, identify patterns and key metrics, save analysis to /tmp/pantheon_v2/sheets_analysis.md",
        "variables": ["spreadsheet_id", "range"],
        "tags": ["sheets", "analyze", "google"],
        "estimated_minutes": 4,
    },
    # ── Trading (Task 32) ───────────────────────────────────────────────
    {
        "id": "stock_analysis",
        "category": "trading",
        "title": "Stock Technical Analysis",
        "description": "Market data + technical-style commentary saved to workspace",
        "command": "Get market data for {symbol}, analyze technical indicators including RSI, moving averages, volume trends, recent news sentiment, and provide a comprehensive analysis report saved to /tmp/pantheon_v2/analysis_{symbol}.md",
        "variables": ["symbol"],
        "tags": ["trading", "analysis", "stocks"],
        "estimated_minutes": 6,
    },
    {
        "id": "portfolio_report",
        "category": "trading",
        "title": "Portfolio Performance Report",
        "description": "Multi-symbol read and portfolio summary",
        "command": "Analyze these stocks: {symbols}, calculate portfolio performance, identify best and worst performers, generate risk assessment and save report to /tmp/pantheon_v2/portfolio_report.md",
        "variables": ["symbols"],
        "tags": ["trading", "portfolio", "report"],
        "estimated_minutes": 8,
    },
    {
        "id": "market_screener",
        "category": "trading",
        "title": "Market Stock Screener",
        "description": "Screen ideas using market_data tool",
        "command": "Screen NSE stocks with P/E less than 15, positive last quarter earnings, market cap above 5000 crore, save top 20 results to /tmp/pantheon_v2/screener_results.md",
        "tags": ["trading", "screening", "stocks"],
        "estimated_minutes": 10,
    },
    # ── Website builder (Task 33) ───────────────────────────────────────
    {
        "id": "business_website",
        "category": "build",
        "title": "Business Landing Page",
        "description": "AI-generated landing page in workspace",
        "command": "Create a professional landing page for {business_name}, tagline: {tagline}, description: {description}, key features: {features}, contact: {email}. Save to workspace and show preview path.",
        "variables": ["business_name", "tagline", "description", "features", "email"],
        "tags": ["website", "landing", "build"],
        "estimated_minutes": 8,
    },
    {
        "id": "medical_website",
        "category": "medical",
        "title": "Medical Clinic Website",
        "description": "Clinic site with medical color scheme",
        "command": "Create a professional medical clinic website for {clinic_name}, specialization: {specialization}, doctor: Dr. {doctor_name}, location: {city}, phone: {phone}. Use medical color scheme with trust elements.",
        "variables": ["clinic_name", "specialization", "doctor_name", "city", "phone"],
        "tags": ["website", "medical", "clinic"],
        "estimated_minutes": 10,
    },
    # ── Content (Task 34) ─────────────────────────────────────────────
    {
        "id": "linkedin_post",
        "category": "communicate",
        "title": "LinkedIn Post Writer",
        "description": "Engaging LinkedIn post saved to workspace",
        "command": "Write an engaging LinkedIn post about {topic} for {industry} audience, goal is {goal}, include relevant hashtags, professional tone, 150-200 words. Save to workspace.",
        "variables": ["topic", "industry", "goal"],
        "tags": ["content", "linkedin", "marketing"],
        "estimated_minutes": 3,
    },
    {
        "id": "blog_post",
        "category": "communicate",
        "title": "SEO Blog Post Writer",
        "description": "Long-form SEO blog draft",
        "command": "Write a 1000-word SEO-optimized blog post about {topic}, targeting keywords {keywords}, for {target_audience} audience. Include H1, H2 headings, meta description. Save as /tmp/pantheon_v2/content/blog_{topic}.md",
        "variables": ["topic", "keywords", "target_audience"],
        "tags": ["content", "blog", "seo"],
        "estimated_minutes": 12,
    },
    {
        "id": "product_description",
        "category": "communicate",
        "title": "Product Description Writer",
        "description": "Multi-channel product copy",
        "command": "Write compelling product descriptions for {product_name}: features {features}, benefits {benefits}, target customer {customer}. Create versions for: website, Amazon listing, WhatsApp catalog. Save all to workspace.",
        "variables": ["product_name", "features", "benefits", "customer"],
        "tags": ["content", "product", "ecommerce"],
        "estimated_minutes": 6,
    },
    {
        "id": "biovital_content",
        "category": "medical",
        "title": "BioVital India Content Pack",
        "description": "Hydrogen water bottle marketing pack",
        "command": "Create a complete content pack for BioVital India hydrogen water bottle: 5 Instagram captions with hashtags, 2 LinkedIn posts, 1 WhatsApp catalog description, 1 Amazon product listing. Save all to /tmp/pantheon_v2/content/biovital_pack.md",
        "tags": ["content", "medical", "biovital"],
        "estimated_minutes": 8,
    },
    # ── Finance (Task 35) ─────────────────────────────────────────────
    {
        "id": "gst_report",
        "category": "finance",
        "title": "Monthly GST Report",
        "description": "GST summary from CSV path",
        "command": "Read transaction data from {csv_path}, calculate GST liability for {month}, generate GSTR-1 summary with tax breakup by rate (5%, 12%, 18%, 28%), save as /tmp/pantheon_v2/gst_report_{month}.md",
        "variables": ["csv_path", "month"],
        "tags": ["finance", "gst", "tax"],
        "estimated_minutes": 5,
    },
    {
        "id": "invoice_create",
        "category": "finance",
        "title": "Professional Invoice Generator",
        "description": "GST invoice HTML + markdown",
        "command": "Create a professional GST invoice for client {client_name}, GSTIN {client_gstin}, for {product_service} worth Rs.{amount} plus {gst_rate}% GST, invoice number {invoice_no}, due date {due_date}. Save as HTML and markdown.",
        "variables": [
            "client_name",
            "client_gstin",
            "product_service",
            "amount",
            "gst_rate",
            "invoice_no",
            "due_date",
        ],
        "tags": ["finance", "invoice", "gst"],
        "estimated_minutes": 4,
    },
    {
        "id": "pnl_monthly",
        "category": "finance",
        "title": "Monthly P&L Statement",
        "description": "P&L with margins",
        "command": "Generate monthly P&L statement for {company_name} for {month}: revenue {revenue}, cost of goods {cogs}, operating expenses {opex}. Calculate gross margin, net profit, EBITDA. Save formatted report.",
        "variables": ["company_name", "month", "revenue", "cogs", "opex"],
        "tags": ["finance", "pnl", "accounting"],
        "estimated_minutes": 5,
    },
    {
        "id": "pantheon_med_invoice",
        "category": "medical",
        "title": "Pantheon Meditech Invoice",
        "description": "Medical equipment GST invoice",
        "command": "Create a GST invoice from Pantheon Meditech Private Limited (Salem, Tamil Nadu) to client {client_name} for {equipment_name} worth Rs.{amount}. Include HSN code for medical equipment, 12% GST, company details. Save as professional HTML invoice.",
        "variables": ["client_name", "equipment_name", "amount"],
        "tags": ["medical", "invoice", "pantheon"],
        "estimated_minutes": 4,
    },
    # ── CTO / code (Task 36) ──────────────────────────────────────────
    {
        "id": "build_api",
        "category": "build",
        "title": "Build FastAPI Backend",
        "description": "Scaffold API in workspace",
        "command": "Create a complete FastAPI backend for {app_name} with endpoints: {endpoints}. Include SQLite database, authentication, CORS, and save to /tmp/pantheon_v2/projects/{app_name}/",
        "variables": ["app_name", "endpoints"],
        "tags": ["code", "api", "fastapi"],
        "estimated_minutes": 6,
    },
    {
        "id": "generate_tests_template",
        "category": "build",
        "title": "Generate Unit Tests",
        "description": "Create tests from source file",
        "command": "Using code_builder generate_tests, create pytest tests for the Python module at {source_path} and save alongside the file with test_ prefix.",
        "variables": ["source_path"],
        "tags": ["code", "tests", "pytest"],
        "estimated_minutes": 5,
    },
    # ── Brand (Task 37) ───────────────────────────────────────────────
    {
        "id": "personal_brand_audit",
        "category": "communicate",
        "title": "Personal Brand Audit",
        "description": "Full brand guide in workspace",
        "command": "Analyze my personal brand for {name} in {industry}. Research my target audience {audience}, create content pillars, 30-day posting calendar for LinkedIn and Twitter, hashtag strategy, and engagement plan. Save complete brand guide to workspace.",
        "variables": ["name", "industry", "audience"],
        "tags": ["brand", "social", "strategy"],
        "estimated_minutes": 12,
    },
    {
        "id": "viral_post_generator",
        "category": "communicate",
        "title": "Viral Post Generator",
        "description": "10 LinkedIn-style ideas",
        "command": "Create 10 viral LinkedIn post ideas for {topic} in {industry}. For each: attention-grabbing hook, full post body (150 words), call-to-action, 5 hashtags. Make them shareable and engaging. Save to workspace.",
        "variables": ["topic", "industry"],
        "tags": ["content", "viral", "linkedin"],
        "estimated_minutes": 8,
    },
    {
        "id": "nishant_brand",
        "category": "communicate",
        "title": "Nishant's Brand Content",
        "description": "Executive LinkedIn week pack",
        "command": "Create a week of LinkedIn content for Nishant Agarwal, CEO of Pantheon Meditech (medical equipment) and founder of Pantheon COO OS (AI automation). Topics: medical technology, AI automation for business, entrepreneurship in India. Professional but approachable tone. 5 posts with hooks.",
        "tags": ["content", "personal", "linkedin"],
        "estimated_minutes": 10,
    },
    # ── PantheonMed vertical (medical / healthcare) ─────────────────────
    {
        "id": "inventory_check",
        "category": "medical",
        "title": "Medical Equipment Inventory Check",
        "description": "Check stock levels and generate reorder list",
        "command": "Read the inventory file at {inventory_path}, identify items below reorder threshold {threshold}, create a purchase order draft at /tmp/pantheon_v2/purchase_order_{date}.md with supplier details",
        "variables": ["inventory_path", "threshold", "date"],
        "tags": ["medical", "inventory", "procurement"],
        "estimated_minutes": 4,
    },
    {
        "id": "patient_report_summary",
        "category": "medical",
        "title": "Daily Patient Report Summary",
        "description": "Summarize daily patient data into a structured report",
        "command": "Read patient data from {data_path}, calculate key statistics (count, avg wait time, department breakdown), generate a formatted daily report and save to /tmp/pantheon_v2/patient_report_{date}.md",
        "variables": ["data_path", "date"],
        "tags": ["medical", "report", "patients"],
        "estimated_minutes": 5,
    },
    {
        "id": "supplier_email",
        "category": "medical",
        "title": "Supplier Quotation Request",
        "description": "Email suppliers requesting quotation for equipment",
        "command": "Write a professional quotation request email for {equipment_name} with quantity {quantity}, technical specifications {specs}, delivery timeline {timeline}, send to {supplier_email} from our company Pantheon Meditech",
        "variables": ["equipment_name", "quantity", "specs", "timeline", "supplier_email"],
        "tags": ["medical", "procurement", "email"],
        "estimated_minutes": 3,
    },
    {
        "id": "compliance_checklist",
        "category": "medical",
        "title": "Equipment Compliance Check",
        "description": "Generate compliance checklist for medical equipment",
        "command": "Create a regulatory compliance checklist for {equipment_type} as per Indian medical device regulations (MDR 2017), save as /tmp/pantheon_v2/compliance_{equipment_type}.md",
        "variables": ["equipment_type"],
        "tags": ["medical", "compliance", "regulatory"],
        "estimated_minutes": 4,
    },
    {
        "id": "call_supplier",
        "category": "communicate",
        "title": "Call Supplier for Quotation",
        "description": "Outbound call to request quotation",
        "command": "Call {phone_number} and speak with {contact_name}. Request quotation for {product} quantity {quantity}. Our company is Pantheon Meditech Salem Tamil Nadu. Note down the price and delivery timeline.",
        "variables": ["phone_number", "contact_name", "product", "quantity"],
        "tags": ["call", "supplier", "quotation"],
        "estimated_minutes": 3,
    },
    {
        "id": "call_followup",
        "category": "communicate",
        "title": "Follow-up Call",
        "description": "Sales follow-up on a proposal",
        "command": "Call {phone_number} to follow up on our proposal sent on {date}. Ask if they have reviewed it and if they have any questions about {product}.",
        "variables": ["phone_number", "date", "product"],
        "tags": ["call", "followup", "sales"],
        "estimated_minutes": 2,
    },
    {
        "id": "medical_appointment",
        "category": "medical",
        "title": "Schedule Demo Appointment Call",
        "description": "Call a doctor to schedule HBOT demo",
        "command": "Call Dr. {doctor_name} at {phone_number} from {hospital}. Schedule a product demonstration of our HBOT chamber. Suggest dates: {dates}. Confirm appointment and save to calendar.",
        "variables": ["doctor_name", "phone_number", "hospital", "dates"],
        "tags": ["call", "medical", "appointment"],
        "estimated_minutes": 4,
    },
    {
        "id": "sms_blast",
        "category": "communicate",
        "title": "SMS Notification",
        "description": "Send SMS via Twilio",
        "command": "Send SMS to {phone_number}: {message}",
        "variables": ["phone_number", "message"],
        "tags": ["sms", "notify", "phone"],
        "estimated_minutes": 1,
    },
    {
        "id": "db_report",
        "category": "analyze",
        "title": "Database Query Report",
        "description": "Run a sandboxed query and save a report",
        "command": "Connect to database {connection_string}, run query: {query}, format results as a readable report and save to /tmp/pantheon_v2/db_report.md",
        "variables": ["connection_string", "query"],
        "tags": ["database", "query", "report"],
        "estimated_minutes": 5,
    },
    {
        "id": "db_backup",
        "category": "devops",
        "title": "SQLite Database Backup",
        "description": "Backup SQLite database under workspace",
        "command": "Backup SQLite database at {db_path} to /tmp/pantheon_v2/backups/backup_{timestamp}.db",
        "variables": ["db_path", "timestamp"],
        "tags": ["database", "backup", "devops"],
        "estimated_minutes": 2,
    },
    {
        "id": "invoice_pdf",
        "category": "finance",
        "title": "PDF Invoice Generator",
        "description": "Generate GST invoice PDF",
        "command": "Generate a professional PDF invoice for {client_name} for {product_service} worth Rs.{amount} with 18% GST. Invoice number {invoice_no}. Save as PDF.",
        "variables": ["client_name", "product_service", "amount", "invoice_no"],
        "tags": ["pdf", "invoice", "finance"],
        "estimated_minutes": 3,
    },
    {
        "id": "report_pdf",
        "category": "reporting",
        "title": "PDF Report Generator",
        "description": "Convert report content to PDF",
        "command": "Convert the report at {file_path} into a professional PDF with title {title}, company header Pantheon Meditech, save to workspace.",
        "variables": ["file_path", "title"],
        "tags": ["pdf", "report", "document"],
        "estimated_minutes": 4,
    },
    {
        "id": "invoice_scan",
        "category": "finance",
        "title": "Invoice/Receipt Scanner",
        "description": "Vision extraction from invoice images",
        "command": "Analyze the invoice/receipt image at {image_path}, extract all financial data (vendor, amount, date, items, GST), and save structured data to /tmp/pantheon_v2/scanned_invoice.md",
        "variables": ["image_path"],
        "tags": ["image", "ocr", "invoice"],
        "estimated_minutes": 5,
    },
    {
        "id": "document_ocr",
        "category": "analyze",
        "title": "Document Text Extractor",
        "description": "OCR document images",
        "command": "Extract all text from the document image at {image_path} using OCR, clean and format the text, save to /tmp/pantheon_v2/extracted_text.txt",
        "variables": ["image_path"],
        "tags": ["image", "ocr", "document"],
        "estimated_minutes": 3,
    },
    {
        "id": "daily_news_brief",
        "category": "reporting",
        "title": "Daily Industry News Brief",
        "description": "News digest and synthesis",
        "command": "Search for latest news about {topic} in India, find top 10 relevant articles, summarize key insights, identify opportunities and threats for our business. Save as /tmp/pantheon_v2/news_brief_{date}.md",
        "variables": ["topic", "date"],
        "tags": ["news", "research", "brief"],
        "estimated_minutes": 8,
    },
    {
        "id": "competitor_news",
        "category": "research",
        "title": "Competitor News Monitor",
        "description": "Track competitor announcements",
        "command": "Search for recent news about {competitor_name} in medical equipment industry. Find announcements, product launches, funding, partnerships. Save analysis to workspace.",
        "variables": ["competitor_name"],
        "tags": ["competitor", "news", "monitor"],
        "estimated_minutes": 6,
    },
    {
        "id": "medical_device_news",
        "category": "medical",
        "title": "Medical Device Industry News",
        "description": "HBOT, hydrotherapy, PEMF, hydrogen water in India",
        "command": "Get latest news about HBOT, colon hydrotherapy, PEMF therapy, hydrogen water in India. Find regulatory updates, new products, market trends. Save comprehensive report.",
        "tags": ["medical", "news", "industry"],
        "estimated_minutes": 10,
    },
    {
        "id": "website_security_audit",
        "category": "devops",
        "title": "Website Security Audit",
        "description": "SSL, headers, score",
        "command": "Perform a complete security audit of {url}. Check SSL certificate, security headers, known vulnerabilities. Generate score out of 100 and save detailed report with remediation steps.",
        "variables": ["url"],
        "tags": ["security", "audit", "website"],
        "estimated_minutes": 6,
    },
    {
        "id": "ssl_monitor",
        "category": "devops",
        "title": "SSL Certificate Monitor",
        "description": "Track certificate expiry",
        "command": "Check SSL certificate for {domain}. If expiry within 30 days, send alert email to {email}.",
        "variables": ["domain", "email"],
        "tags": ["ssl", "security", "monitor"],
        "estimated_minutes": 2,
    },
    {
        "id": "cdsco_checklist",
        "category": "medical",
        "title": "CDSCO Compliance Checklist",
        "description": "Medical device rules 2017 checklist",
        "command": "Generate CDSCO Medical Device Rules 2017 compliance checklist for {device_name}, Class {device_class} medical device. Include all required documentation, testing, and registration requirements.",
        "variables": ["device_name", "device_class"],
        "tags": ["compliance", "medical", "cdsco"],
        "estimated_minutes": 8,
    },
    {
        "id": "gstin_validator",
        "category": "finance",
        "title": "GSTIN Bulk Validator",
        "description": "Validate GSTIN list",
        "command": "Validate these GSTINs: {gstin_list}. Check format, state codes, checksum. Generate validation report.",
        "variables": ["gstin_list"],
        "tags": ["gst", "validation", "compliance"],
        "estimated_minutes": 3,
    },
    {
        "id": "nda_generator",
        "category": "communicate",
        "title": "NDA Document Generator",
        "description": "Template NDA (legal review required)",
        "command": "Create an NDA between {party1_name} and {party2_name} for purpose: {purpose}. Duration {years} years. Save as /tmp/pantheon_v2/legal/nda_{party1}_{party2}.md with full legal template.",
        "variables": ["party1_name", "party2_name", "purpose", "years"],
        "tags": ["legal", "nda", "document"],
        "estimated_minutes": 4,
    },
    {
        "id": "deploy_website",
        "category": "build",
        "title": "Build + Deploy Website",
        "description": "Landing page, GitHub, Vercel",
        "command": "Create a landing page for {business_name} with tagline {tagline}, then create GitHub repo {repo_name}, push the code, and deploy to Vercel. Return the live URL.",
        "variables": ["business_name", "tagline", "repo_name"],
        "tags": ["deploy", "website", "github"],
        "estimated_minutes": 20,
    },
    {
        "id": "deploy_api",
        "category": "build",
        "title": "Deploy FastAPI to Railway",
        "description": "Railway CLI deploy",
        "command": "Deploy the FastAPI project at {project_path} to Railway as service {service_name} on port 8000. Set environment variables: {env_vars}. Return live URL.",
        "variables": ["project_path", "service_name", "env_vars"],
        "tags": ["deploy", "railway", "api"],
        "estimated_minutes": 15,
    },
    {
        "id": "product_video_script",
        "category": "communicate",
        "title": "Product Video Script",
        "description": "Script and shot list",
        "command": "Create a 60-second product demo video script for {product_name}. Features: {features}. Target audience: {audience}. Include hook, problem, solution, CTA. Save script and shot list to workspace.",
        "variables": ["product_name", "features", "audience"],
        "tags": ["video", "script", "marketing"],
        "estimated_minutes": 8,
    },
    {
        "id": "biovital_video",
        "category": "medical",
        "title": "BioVital Hydrogen Bottle Video",
        "description": "Instagram Reel script",
        "command": "Create a 30-second Instagram Reel script for BioVital India hydrogen water bottle. Benefits: antioxidant, energy boost, gut health. Target: health-conscious Indians 25-45. Include hook in Hindi and English, demo shots, WhatsApp CTA.",
        "tags": ["video", "biovital", "instagram"],
        "estimated_minutes": 6,
    },
    {
        "id": "notion_report",
        "category": "reporting",
        "title": "Save Report to Notion",
        "description": "Page under parent",
        "command": "Generate a comprehensive report about {topic}, then create a Notion page in {parent_page_id} with the report content, proper headings and formatting.",
        "variables": ["topic", "parent_page_id"],
        "tags": ["notion", "report", "document"],
        "estimated_minutes": 10,
    },
    {
        "id": "notion_meeting_notes",
        "category": "communicate",
        "title": "Meeting Notes to Notion",
        "description": "Append structured notes",
        "command": "Create meeting notes for {meeting_title} in Notion page {page_id}. Attendees: {attendees}. Topics: {topics}. Include action items section.",
        "variables": ["meeting_title", "page_id", "attendees", "topics"],
        "tags": ["notion", "meeting", "notes"],
        "estimated_minutes": 5,
    },
    {
        "id": "lead_capture",
        "category": "communicate",
        "title": "Capture Lead in Zoho CRM",
        "description": "New Zoho lead",
        "command": "Create a new lead in Zoho CRM for {name} from {company}, email {email}, phone {phone}. Source: {source}. Add note: {notes}.",
        "variables": ["name", "company", "email", "phone", "source", "notes"],
        "tags": ["crm", "lead", "zoho"],
        "estimated_minutes": 2,
    },
    {
        "id": "crm_report",
        "category": "reporting",
        "title": "CRM Pipeline Report",
        "description": "Search and summarize pipeline",
        "command": "Search Zoho CRM for all leads in {stage} stage, generate a pipeline report with total value, count by source, and list of next follow-ups needed. Save to workspace.",
        "variables": ["stage"],
        "tags": ["crm", "pipeline", "report"],
        "estimated_minutes": 12,
    },
    {
        "id": "medical_lead",
        "category": "medical",
        "title": "Medical Equipment Lead",
        "description": "HBOT prospect in Zoho",
        "command": "Create a lead in Zoho CRM for potential HBOT buyer: {doctor_name}, {hospital_name}, {city}. Email: {email}. Phone: {phone}. Add to HBOT Prospects pipeline.",
        "variables": ["doctor_name", "hospital_name", "city", "email", "phone"],
        "tags": ["medical", "crm", "lead"],
        "estimated_minutes": 3,
    },
    {
        "id": "schedule_meeting",
        "category": "communicate",
        "title": "Schedule Meeting",
        "description": "Calendar event + Meet",
        "command": "Schedule a meeting with {attendees} on {date} at {time} for {duration} minutes. Title: {title}. Add Google Meet link. Send calendar invite.",
        "variables": ["attendees", "date", "time", "duration", "title"],
        "tags": ["calendar", "meeting", "schedule"],
        "estimated_minutes": 3,
    },
    {
        "id": "weekly_schedule",
        "category": "reporting",
        "title": "Weekly Schedule Report",
        "description": "Pull week events and summarize",
        "command": "Get all calendar events for next week, generate a formatted schedule report with meeting counts, busy vs free hours, and preparation notes for each meeting. Save to workspace.",
        "tags": ["calendar", "schedule", "weekly"],
        "estimated_minutes": 8,
    },
    {
        "id": "demo_schedule",
        "category": "medical",
        "title": "HBOT Demo Scheduling",
        "description": "Demo call on calendar",
        "command": "Schedule a product demo call with Dr. {doctor_name} from {hospital} on {date} at {time}. Title: Pantheon Meditech - HBOT Demo. Duration: 45 minutes. Add to calendar and send confirmation.",
        "variables": ["doctor_name", "hospital", "date", "time"],
        "tags": ["medical", "demo", "calendar"],
        "estimated_minutes": 4,
    },
    {
        "id": "tally_sync",
        "category": "finance",
        "title": "Sync Invoices to Tally",
        "description": "Import invoice JSON files as Tally Sales vouchers",
        "command": "Read all invoice files from /tmp/pantheon_v2/invoices/, sync them to Tally Prime as Sales vouchers for company {company_name}. Report success/failure count.",
        "variables": ["company_name"],
        "tags": ["tally", "accounting", "sync"],
        "estimated_minutes": 6,
    },
    {
        "id": "tally_balance",
        "category": "finance",
        "title": "Tally Account Balance",
        "description": "Ledger balance for a period",
        "command": "Get balance of ledger {ledger_name} from Tally for period {from_date} to {to_date}. Show opening balance, transactions, closing balance.",
        "variables": ["ledger_name", "from_date", "to_date"],
        "tags": ["tally", "balance", "accounting"],
        "estimated_minutes": 4,
    },
    {
        "id": "pantheon_med_tally",
        "category": "medical",
        "title": "Pantheon Meditech Tally Report",
        "description": "Trial balance and expense snapshot",
        "command": "Get trial balance from Tally for Pantheon Meditech for current financial year. Identify top 5 expense heads, revenue vs last month. Save formatted report.",
        "tags": ["tally", "medical", "finance"],
        "estimated_minutes": 8,
    },
    {
        "id": "amazon_daily_report",
        "category": "reporting",
        "title": "Amazon Daily Sales Report",
        "description": "Amazon sales analysis and low-stock report",
        "command": "Get Amazon sales data for last 7 days, analyze top-selling products, calculate revenue, identify low-stock items, send daily report to {email}",
        "variables": ["email"],
        "tags": ["amazon", "sales", "report"],
        "estimated_minutes": 5,
    },
    {
        "id": "amazon_inventory_alert",
        "category": "devops",
        "title": "Amazon Inventory Monitor",
        "description": "Low-stock alerts and restock quantities",
        "command": "Check Amazon inventory for all products. Alert for items below {threshold} units. Generate restock report with recommended quantities.",
        "variables": ["threshold"],
        "tags": ["amazon", "inventory", "alert"],
        "estimated_minutes": 4,
    },
    {
        "id": "amazon_review_monitor",
        "category": "research",
        "title": "Amazon Review Analyzer",
        "description": "Mine low-star reviews for product insights",
        "command": "Get all 1-3 star reviews for product {asin} from Amazon. Analyze common complaints, identify product improvement opportunities, generate summary report.",
        "variables": ["asin"],
        "tags": ["amazon", "reviews", "analyze"],
        "estimated_minutes": 6,
    },
    {
        "id": "meesho_orders",
        "category": "reporting",
        "title": "Meesho Daily Orders",
        "description": "Meesho order summary and shipping checklist",
        "command": "Get today's Meesho orders, check for any cancellations, identify orders needing shipping, generate pickup summary.",
        "tags": ["meesho", "orders", "ecommerce"],
        "estimated_minutes": 3,
    },
    {
        "id": "biovital_meesho",
        "category": "medical",
        "title": "BioVital Meesho Report",
        "description": "BioVital performance on Meesho",
        "command": "Get BioVital India product performance on Meesho for last 30 days. Sales count, revenue, return rate, top-selling variants. Save report to workspace.",
        "tags": ["meesho", "biovital", "report"],
        "estimated_minutes": 8,
    },
    {
        "id": "whatsapp_broadcast",
        "category": "communicate",
        "title": "WhatsApp Offer Broadcast",
        "description": "Opt-in promotional broadcast from CSV",
        "command": "Read opt-in customer list from {csv_path}, send WhatsApp promotional message: {message} to all customers. Track delivery status.",
        "variables": ["csv_path", "message"],
        "tags": ["whatsapp", "broadcast", "marketing"],
        "estimated_minutes": 10,
    },
    {
        "id": "biovital_whatsapp",
        "category": "medical",
        "title": "BioVital WhatsApp Campaign",
        "description": "Localized campaign for hydrogen water bottle",
        "command": "Create WhatsApp marketing campaign for BioVital hydrogen water bottle. Message in Hindi and English. Send to customers in {city}. Include product image placeholder and buy link.",
        "variables": ["city"],
        "tags": ["whatsapp", "biovital", "campaign"],
        "estimated_minutes": 6,
    },
    {
        "id": "uae_vat_invoice",
        "category": "finance",
        "title": "UAE VAT Invoice (TRN)",
        "description": "UAE 5% VAT compliant invoice",
        "command": "Create a UAE-compliant VAT invoice for {client_name}, TRN: {trn_number}, for {service} worth AED {amount} with 5% VAT. Include mandatory UAE VAT fields.",
        "variables": ["client_name", "trn_number", "service", "amount"],
        "tags": ["uae", "vat", "invoice", "finance"],
        "estimated_minutes": 5,
    },
    {
        "id": "arabic_proposal",
        "category": "communicate",
        "title": "Arabic Business Proposal",
        "description": "Professional Arabic proposal for UAE market",
        "command": "Write a professional business proposal in Arabic for {company_name} for {service}. Include executive summary, scope, timeline, pricing in AED.",
        "variables": ["company_name", "service"],
        "tags": ["arabic", "proposal", "uae"],
        "estimated_minutes": 12,
    },
    {
        "id": "us_invoice",
        "category": "finance",
        "title": "US Business Invoice",
        "description": "US-format invoice Net-30",
        "command": "Create a US-format invoice for {client_name} for {service} worth ${amount}. Include payment terms Net-30, wire transfer details.",
        "variables": ["client_name", "service", "amount"],
        "tags": ["us", "invoice", "dollar"],
        "estimated_minutes": 4,
    },
    {
        "id": "cold_email_us",
        "category": "communicate",
        "title": "US Cold Outreach Email",
        "description": "Short American English outreach",
        "command": "Write a cold email to {name} at {company} about {product}. American English, casual professional tone, under 150 words, specific value prop, clear CTA.",
        "variables": ["name", "company", "product"],
        "tags": ["email", "outreach", "us"],
        "estimated_minutes": 3,
    },
    {
        "id": "german_datenschutz",
        "category": "communicate",
        "title": "GDPR Privacy Notice (German)",
        "description": "German Datenschutzerklärung",
        "command": "Create a GDPR-compliant Datenschutzerklärung (privacy policy) in German for {company_name} website {website_url}. Include all required GDPR sections.",
        "variables": ["company_name", "website_url"],
        "tags": ["gdpr", "privacy", "german", "legal"],
        "estimated_minutes": 15,
    },
    {
        "id": "nota_fiscal",
        "category": "finance",
        "title": "Brazilian Nota Fiscal",
        "description": "Brazil tax document structure",
        "command": "Create a Brazilian Nota Fiscal structure for {company_name}, CNPJ {cnpj}, for {product} worth R${amount}. Include ICMS, ISS tax fields.",
        "variables": ["company_name", "cnpj", "product", "amount"],
        "tags": ["brazil", "nota_fiscal", "tax"],
        "estimated_minutes": 8,
    },
    {
        "id": "japanese_keigo_email",
        "category": "communicate",
        "title": "Japanese Business Email (敬語)",
        "description": "Keigo business correspondence",
        "command": "Write a Japanese business email in keigo (honorific language) to {recipient_company} about {subject}. Proper salutation, humble language, polite closing.",
        "variables": ["recipient_company", "subject"],
        "tags": ["japanese", "keigo", "business", "email"],
        "estimated_minutes": 6,
    },
    {
        "id": "nigeria_business_letter",
        "category": "communicate",
        "title": "Nigerian Business Letter",
        "description": "Formal Nigerian English letter",
        "command": "Write a formal business letter for {company_name} in Nigeria to {recipient} about {subject}. Nigerian English conventions, formal style.",
        "variables": ["company_name", "recipient", "subject"],
        "tags": ["nigeria", "africa", "business", "letter"],
        "estimated_minutes": 5,
    },
    {
        "id": "indonesia_proposal",
        "category": "communicate",
        "title": "Indonesian Business Proposal (Bahasa)",
        "description": "Formal Indonesian proposal",
        "command": "Write a professional proposal in Bahasa Indonesia for {company_name} regarding {service}. Formal Indonesian business language.",
        "variables": ["company_name", "service"],
        "tags": ["indonesia", "bahasa", "proposal"],
        "estimated_minutes": 10,
    },
    {
        "id": "zapier_notify",
        "category": "communicate",
        "title": "Send Data to Zapier",
        "description": "POST JSON to a Zapier Catch Hook",
        "command": "Send this data to Zapier webhook {webhook_url}: {data}. Trigger automated workflow.",
        "variables": ["webhook_url", "data"],
        "tags": ["zapier", "automation", "webhook"],
        "estimated_minutes": 2,
    },
    {
        "id": "hubspot_lead",
        "category": "communicate",
        "title": "Add Lead to HubSpot",
        "description": "Create contact and deal in HubSpot",
        "command": "Create HubSpot contact for {name} at {company}, email {email}. Create deal: {deal_name} worth ${amount} in {stage} stage.",
        "variables": ["name", "company", "email", "deal_name", "amount", "stage"],
        "tags": ["hubspot", "crm", "lead"],
        "estimated_minutes": 5,
    },
    {
        "id": "hubspot_pipeline",
        "category": "reporting",
        "title": "HubSpot Pipeline Report",
        "description": "Summarize deals by stage",
        "command": "Get all HubSpot deals in pipeline, group by stage, calculate total value, identify stalled deals (no update in 7+ days), save pipeline report to workspace.",
        "tags": ["hubspot", "pipeline", "report"],
        "estimated_minutes": 15,
    },
    {
        "id": "wp_blog_post",
        "category": "communicate",
        "title": "Publish WordPress Blog Post",
        "description": "Draft long-form content in WordPress",
        "command": "Write a 500-word SEO blog post about {topic} for {industry}, then publish it to WordPress as a draft post with title {title}.",
        "variables": ["topic", "industry", "title"],
        "tags": ["wordpress", "blog", "content"],
        "estimated_minutes": 20,
    },
    {
        "id": "shopify_daily_report",
        "category": "reporting",
        "title": "Shopify Daily Sales Report",
        "description": "Orders and inventory snapshot",
        "command": "Get today's Shopify orders and sales data, identify best-selling products, calculate revenue, flag low inventory items, save daily report.",
        "tags": ["shopify", "ecommerce", "report"],
        "estimated_minutes": 12,
    },
    {
        "id": "linkedin_outreach",
        "category": "communicate",
        "title": "LinkedIn B2B Outreach",
        "description": "Search and personalize outreach",
        "command": "Search LinkedIn for {job_title} in {industry} in {city}. Find top 10 profiles. Write personalized connection request for each based on their profile. Send connection requests with custom messages about {product}.",
        "variables": ["job_title", "industry", "city", "product"],
        "tags": ["linkedin", "outreach", "b2b"],
        "estimated_minutes": 15,
    },
    {
        "id": "linkedin_post_creator",
        "category": "communicate",
        "title": "LinkedIn Thought Leadership Post",
        "description": "Long-form LinkedIn content",
        "command": "Create a LinkedIn post about {topic} from perspective of a medical equipment founder in India. Include data points, personal insight, and call-to-action. 200-250 words. Professional but personal tone.",
        "variables": ["topic"],
        "tags": ["linkedin", "content", "thought-leadership"],
        "estimated_minutes": 8,
    },
    {
        "id": "nishant_linkedin",
        "category": "communicate",
        "title": "Nishant Agarwal LinkedIn Post",
        "description": "Founder personal brand",
        "command": "Write a LinkedIn post for Nishant Agarwal, CEO Pantheon Meditech and founder of Pantheon COO OS AI tool. Topic: {topic}. Show expertise in medical equipment AND AI automation. Personal story angle. Include hashtags.",
        "variables": ["topic"],
        "tags": ["linkedin", "personal-brand", "nishant"],
        "estimated_minutes": 8,
    },
    {
        "id": "instagram_product_post",
        "category": "communicate",
        "title": "Instagram Product Post",
        "description": "Caption + hashtags for BioVital",
        "command": "Create an Instagram post for BioVital India hydrogen water bottle. Write engaging caption (max 150 words), 15 relevant hashtags mix of high/medium/low competition, call-to-action to WhatsApp. Save caption and hashtags to workspace.",
        "tags": ["instagram", "biovital", "social"],
        "estimated_minutes": 6,
    },
    {
        "id": "social_media_calendar",
        "category": "communicate",
        "title": "30-Day Social Media Calendar",
        "description": "Cross-platform calendar",
        "command": "Create a 30-day social media content calendar for {brand_name} in {industry}. Platforms: Instagram and LinkedIn. 1 post per day each platform. Mix: educational, promotional, behind-scenes, testimonial. Save as formatted calendar.",
        "variables": ["brand_name", "industry"],
        "tags": ["social", "calendar", "content"],
        "estimated_minutes": 20,
    },
    {
        "id": "gem_bid_search",
        "category": "government",
        "title": "Search GeM Portal Bids",
        "description": "Find active tenders",
        "command": "Search GeM portal for medical equipment tenders in Tamil Nadu category HBOT/oxygen therapy. Find bids closing in next 30 days. List top 5 opportunities with value, deadline, requirements. Save report.",
        "tags": ["gem", "government", "tender"],
        "estimated_minutes": 12,
    },
    {
        "id": "gem_bid_prepare",
        "category": "government",
        "title": "Prepare GeM Bid Document",
        "description": "Structured bid draft",
        "command": "Prepare bid document for GeM tender {bid_id}. Company: Pantheon Meditech Private Limited, Salem TN. Include technical specs, price bid, compliance declarations. Save as formatted PDF structure.",
        "variables": ["bid_id"],
        "tags": ["gem", "bid", "document"],
        "estimated_minutes": 25,
    },
]


def get_template_by_id(template_id: str) -> Optional[dict[str, Any]]:
    for t in TEMPLATES:
        if t["id"] == template_id:
            return dict(t)
    return None


def filter_by_category(templates: list[dict[str, Any]], category: Optional[str]) -> list[dict[str, Any]]:
    if not category:
        return list(templates)
    return [dict(t) for t in templates if t.get("category") == category]


def prioritize_medical_first(templates: list[dict[str, Any]], industry: Optional[str]) -> list[dict[str, Any]]:
    """Medical industry users see medical category templates first."""
    if (industry or "").lower() != "medical":
        return templates
    medical = [dict(t) for t in templates if t.get("category") == "medical"]
    rest = [dict(t) for t in templates if t.get("category") != "medical"]
    return medical + rest


def group_by_category(templates: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for t in templates:
        cat = t.get("category", "general")
        out.setdefault(cat, []).append(dict(t))
    return out


_PLACEHOLDER = re.compile(r"\{([a-zA-Z0-9_]+)\}")


def substitute_variables(command: str, variables: dict[str, str]) -> str:
    """Replace {var} placeholders; missing keys leave placeholder as-is."""

    def repl(m: re.Match[str]) -> str:
        key = m.group(1)
        if key in variables:
            return str(variables[key])
        return m.group(0)

    return _PLACEHOLDER.sub(repl, command)


def validate_industry(value: str) -> str:
    v = (value or "").strip().lower()
    if not v:
        return "other"
    if v in INDUSTRIES:
        return v
    raise ValueError(f"industry must be one of: {', '.join(sorted(INDUSTRIES))}")
