"""
tools/code_builder.py — Scaffolding FastAPI/Telegram bots, code review, tests, docstrings.
"""
from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Any

from config import settings
from agents.model_router import call_model
from models import CodeReviewOutput

def _ws_root() -> Path:
    return Path(settings.workspace_dir).resolve()


def _slug(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_-]+", "-", (name or "app").strip().lower())[:60].strip("-")
    return s or "app"


def _ensure_ws_path(path_str: str) -> Path:
    p = Path(path_str).resolve()
    ws = _ws_root()
    try:
        p.relative_to(ws)
    except ValueError:
        raise ValueError("path must be under workspace_dir")
    return p


async def _create_fastapi_app(p: dict[str, Any]) -> dict[str, Any]:
    app_name = str(p.get("app_name") or "myapp").strip()
    endpoints = p.get("endpoints") or [{"path": "/health", "method": "GET"}]
    db = str(p.get("database") or "sqlite")
    auth = bool(p.get("auth", False))
    root = _ws_root() / "projects" / _slug(app_name)
    root.mkdir(parents=True, exist_ok=True)
    ep_lines = "\n".join(
        f'@app.{str(e.get("method","get")).lower()}("{e.get("path", "/")}")\nasync def ep_{i}():\n    return {{"ok": True}}\n'
        for i, e in enumerate(endpoints)
    )
    main_py = f'''"""
{app_name} — generated by Pantheon COO code_builder.
"""
from fastapi import FastAPI

app = FastAPI(title="{app_name}")

{ep_lines}

@app.get("/")
async def root():
    return {{"app": "{app_name}", "db": "{db}", "auth": {auth}}}
'''
    models_py = '"""ORM models placeholder."""\nfrom typing import Any\n'
    req = "fastapi\nuvicorn[standard]\n"
    if db == "postgres":
        req += "asyncpg\n"
    readme = f"# {app_name}\n\nRun: `uvicorn main:app --reload`\n"
    (root / "main.py").write_text(main_py, encoding="utf-8")
    (root / "models.py").write_text(models_py, encoding="utf-8")
    (root / "requirements.txt").write_text(req, encoding="utf-8")
    (root / "README.md").write_text(readme, encoding="utf-8")
    return {"project_path": str(root), "files": ["main.py", "models.py", "requirements.txt", "README.md"]}


async def _create_telegram_bot(p: dict[str, Any]) -> dict[str, Any]:
    name = str(p.get("bot_name") or "mybot").strip()
    cmds = p.get("commands") or [{"command": "start", "description": "Start", "handler": "on_start"}]
    root = _ws_root() / "projects" / _slug(name + "_tg_bot")
    root.mkdir(parents=True, exist_ok=True)
    lines = "\n".join(
        f"# /{c.get('command')} — {c.get('description','')}\ndef {c.get('handler','handler')}():\n    pass\n"
        for c in cmds
    )
    bot_py = f'''"""
Telegram bot scaffold: {name}
"""
import os
import httpx

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_TOKEN_HERE")

{lines}

async def webhook(update: dict):
    return {{"ok": True}}
'''
    (root / "bot.py").write_text(bot_py, encoding="utf-8")
    return {"project_path": str(root), "file": "bot.py"}


async def _run_code_review(p: dict[str, Any]) -> dict[str, Any]:
    fp = _ensure_ws_path(str(p.get("file_path") or ""))
    lang = str(p.get("language") or "python")
    src = fp.read_text(encoding="utf-8")[:20000]
    system = f"You are a code reviewer for {lang}. Return JSON with keys issues (list), suggestions (list), score (int 0-100)."
    user = f"Review this code:\n```\n{src}\n```"

    def _sync():
        return call_model(system, user, use_fast=True, max_tokens=2048)

    r = await asyncio.to_thread(_sync)
    raw = (r.text or "").strip()
    if raw.startswith("```"):
        lines = raw.split("\n")
        raw = "\n".join(lines[1:])
        if "```" in raw:
            raw = raw[: raw.rfind("```")]
    try:
        import json

        data = json.loads(raw)
        out = CodeReviewOutput(**data)
    except Exception:
        out = CodeReviewOutput(
            issues=["parse_error"],
            suggestions=[raw[:500]],
            score=50,
        )
    return out.model_dump()


async def _generate_tests(p: dict[str, Any]) -> dict[str, Any]:
    src_path = _ensure_ws_path(str(p.get("source_file_path") or ""))
    framework = str(p.get("framework") or "pytest")
    source = src_path.read_text(encoding="utf-8")[:16000]
    system = f"Write {framework} tests. Return ONLY Python test file body, no fences."
    user = f"Generate tests for:\n```python\n{source}\n```"
    agent = __import__("agents.code_agent", fromlist=["CodeAgent"]).CodeAgent()

    def _sync():
        return call_model(agent.system_prompt, user, use_fast=True, max_tokens=4096)

    r = await asyncio.to_thread(_sync)
    code = (r.text or "").strip()
    if code.startswith("```"):
        lines = code.split("\n")
        code = "\n".join(lines[1:])
        if code.rstrip().endswith("```"):
            code = code[: code.rfind("```")].rstrip()
    out_name = "test_" + src_path.name
    if out_name.endswith(".py") is False:
        out_name += ".py"
    out_path = src_path.parent / out_name
    out_path.write_text(code, encoding="utf-8")
    return {"test_path": str(out_path), "bytes": out_path.stat().st_size}


async def _add_docstrings(p: dict[str, Any]) -> dict[str, Any]:
    fp = _ensure_ws_path(str(p.get("file_path") or ""))
    src = fp.read_text(encoding="utf-8")[:20000]
    agent = __import__("agents.code_agent", fromlist=["CodeAgent"]).CodeAgent()
    user = f"Add or improve docstrings. Return the FULL updated file only.\n\n{src}"

    def _sync():
        return call_model(agent.system_prompt, user, use_fast=True, max_tokens=4096)

    r = await asyncio.to_thread(_sync)
    code = (r.text or "").strip()
    if code.startswith("```"):
        lines = code.split("\n")
        code = "\n".join(lines[1:])
        if "```" in code:
            code = code[: code.rfind("```")].rstrip()
    fp.write_text(code, encoding="utf-8")
    return {"file_path": str(fp), "bytes": fp.stat().st_size}


async def execute(action: str, params: dict[str, Any]) -> Any:
    a = (action or "").strip().lower()
    if a == "create_fastapi_app":
        return await _create_fastapi_app(params)
    if a == "create_react_app":
        raise NotImplementedError("create_react_app not implemented in this build")
    if a == "create_telegram_bot":
        return await _create_telegram_bot(params)
    if a == "create_whatsapp_bot":
        raise NotImplementedError("create_whatsapp_bot not implemented in this build")
    if a == "run_code_review":
        return await _run_code_review(params)
    if a == "generate_tests":
        return await _generate_tests(params)
    if a == "add_feature":
        raise NotImplementedError("add_feature not implemented in this build")
    if a == "add_docstrings":
        return await _add_docstrings(params)
    raise ValueError(f"Unknown code_builder action: {action}")
