"""
tools/registry.py
──────────────────
Dynamic Tool Registry — Phase 3.

Extends the static REGISTRY in tools/__init__.py with hot-loadable
custom tools generated by the Tool Builder Agent.

Custom tools are:
  - Written as Python files to tools/custom/
  - Stored in the custom_tools DB table
  - Loaded at startup (existing tools) and on-demand (new tools)
  - Callable through run_tool() exactly like built-in tools
  - Validated before loading (must export async execute(action, params))

The registry is a singleton — all agents share the same instance.
"""
from __future__ import annotations
import importlib.util
import sys
import asyncio
from pathlib import Path
from typing import Any

CUSTOM_TOOLS_DIR = Path(__file__).parent / "custom"

# Custom tool name → module object
_custom_registry: dict[str, Any] = {}


async def load_all_custom_tools() -> int:
    """Load all tools from DB + disk at startup. Returns count loaded."""
    import memory.store as store
    CUSTOM_TOOLS_DIR.mkdir(parents=True, exist_ok=True)

    tools = await store.get_custom_tools()
    loaded = 0
    for tool in tools:
        try:
            _load_module(tool["tool_name"], tool["module_path"])
            loaded += 1
        except Exception as e:
            print(f"[Registry] Failed to load tool '{tool['tool_name']}': {e}")

    print(f"[Registry] {loaded} custom tool(s) loaded.")
    return loaded


def _load_module(tool_name: str, module_path: str) -> Any:
    """Dynamically import a Python file as a module and register it."""
    path = Path(module_path)
    if not path.exists():
        raise FileNotFoundError(f"Tool module not found: {module_path}")

    spec = importlib.util.spec_from_file_location(f"custom_tool_{tool_name}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    if not hasattr(module, "execute"):
        raise AttributeError(f"Tool module '{tool_name}' must export async execute(action, params)")

    _custom_registry[tool_name] = module
    sys.modules[f"custom_tool_{tool_name}"] = module
    return module


def register_tool(tool_name: str, module_path: str) -> None:
    """Register a newly built tool immediately (no restart needed)."""
    _load_module(tool_name, module_path)
    print(f"[Registry] Tool '{tool_name}' registered live.")


async def run_custom_tool(tool_name: str, action: str, params: dict) -> Any:
    """Execute a custom tool by name."""
    module = _custom_registry.get(tool_name)
    if module is None:
        raise ValueError(
            f"Custom tool '{tool_name}' not found. "
            f"Available: {list(_custom_registry)}"
        )
    import memory.store as store
    await store.increment_tool_usage(tool_name)
    return await module.execute(action, params)


def list_custom_tools() -> list[str]:
    return list(_custom_registry)


def get_custom_tool_module(tool_name: str) -> Any | None:
    return _custom_registry.get(tool_name)
